version: '3.4'

services:

    db:
        image: postgres:latest
        container_name: ${POSTGRES_HOST}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        expose:
            - "5432"
        networks:
            - backend

    web:
        build: .
        depends_on:
            - ${POSTGRES_HOST}
        container_name: ${WEB_HOST}
        environment:
            DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
        expose:
            - "5000"
        links:
            - ${POSTGRES_HOST}
        networks:
            - frontend
            - backend

    proxy:
        build: ./nginx
        container_name: ${PROXY_HOST}
        links:
            - ${WEB_HOST}
        ports:
            - "80:80"
        networks:
            - frontend

networks:
    frontend:
    backend:
