- name: Ensure Docker was installed
    stat:
      path: "/usr/bin/docker"
    register: docker_docker

  - name: Install Docker
    command: 'wget -qO- https://get.docker.com/ | sh'
    become: yes
    when: docker_docker.stat.exists == False
    
   - name: Start service docker, if not running
    service:
      name: docker
      state: started
      enabled: yes
      
      - name: Ensure epel-release is at the latest version
    yum:
      name: epel-release
      state: latest
      
      - name: Installing docker-compose
    command: 'curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose'
    become: yes
    
    - pip:
    name: docker-compose
    version: 1.21.2
